version: "3.9"  # Docker Compose file format version
services:        # Define the services (containers)
  fastapi-app:   # Name of the service
    build:       # Build the Docker image
      context: . # Use the current directory as the build context
      dockerfile: Dockerfile # Use the specified Dockerfile
    ports:       # Map ports between host and container
      - "8000:8000" # Map port 8000 on the host to port 8000 in the container
    volumes:     # Bind-mount local files into the container
      - .:/app   # Mount the current directory into the container at /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload # Override default CMD
